In [4]:
%pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [6]:
import tensorflow
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix
import pandas as pd

In [7]:
# Load the Iris dataset
iris = load_iris()

In [18]:
# Convert data and target into a data frame
# Extract the First (100 + mat number mod 50) Features
X = pd.DataFrame(data=iris.data[:144, :], columns=iris.feature_names)
y = pd.DataFrame(data=iris.target[:144], columns=['irisType'])

In [19]:
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [20]:
# Standardize the data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [21]:
# Convert targets to categorical (one-hot encoding)
y_train = tf.keras.utils.to_categorical(y_train, num_classes=3)
y_test = tf.keras.utils.to_categorical(y_test, num_classes=3)

In [22]:
# Define the Perceptron model using a single dense layer
model = tf.keras.Sequential([
    tf.keras.layers.Dense(3, activation='softmax', input_shape=(X_train.shape[1],))
])

/Users/owner/opt/anaconda3/lib/python3.9/site-packages/keras/src/layers/core/dense.py:88: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [23]:
# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])


In [24]:
# Train the model
model.fit(X_train, y_train, epochs=50, batch_size=1, verbose=1)

Epoch 1/50
115/115 ━━━━━━━━━━━━━━━━━━━━ 1s 845us/step - accuracy: 0.2226 - loss: 1.5920
Epoch 2/50
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 811us/step - accuracy: 0.3097 - loss: 1.2229 
Epoch 3/50
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 0.4482 - loss: 1.0410
Epoch 4/50
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 814us/step - accuracy: 0.7836 - loss: 0.8415
Epoch 5/50
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8122 - loss: 0.7997
Epoch 6/50
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8419 - loss: 0.6470
Epoch 7/50
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8184 - loss: 0.6167
Epoch 8/50
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 935us/step - accuracy: 0.8039 - loss: 0.5854
Epoch 9/50
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 920us/step - accuracy: 0.8162 - loss: 0.5628
Epoch 10/50
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 947us/step - accuracy: 0.8216 - loss: 0.5133
Epoch 11/50
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.8545 - loss: 0.4609
Epoch 12/50
115/115 ━━━━━━━━━━━━━━━

In [25]:
# Make predictions on the test set
y_pred = model.predict(X_test)
y_pred_classes = y_pred.argmax(axis=1)
y_test_classes = y_test.argmax(axis=1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step


In [26]:
# Calculate accuracy of the classifier
accuracy = accuracy_score(y_test_classes, y_pred_classes)
print("Accuracy:", accuracy)


Accuracy: 0.8620689655172413


In [27]:
# Generate the Confusion Matrix
print("Perceptron Confusion Matrix:\n", confusion_matrix(y_test_classes, y_pred_classes))

Perceptron Confusion Matrix:
 [[ 9  0  0]
 [ 0 10  2]
 [ 0  2  6]]
